### KEYBINDS ###

# Reload tmux conf
unbind r
bind r source-file ~/.tmux.conf

# Navigate between panes with vim keybinds
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# Start new windows and tabs on current tab directory
bind c new-window -c "#{pane_current_path}"
bind '"' split-window -c "#{pane_current_path}"
bind '%' split-window -h -c "#{pane_current_path}"

### GLOBALS ###

# Change tmux prefix to control + s
set -g prefix C-s

# Increase terminal history limit
set -g history-limit 9999999

# Enable mouse mode to change between windows, panes, and resizing
set -g mouse on

# Start all new windows on 1 instead of 0
set-option -g base-index 1

### APPEARANCE ###

BLACK="#151820"
GREEN="#97ca72"
GRAY="#343e4f"
FG="#a5b0c5"
BG="#2d3343"

# Move tmux bar to top
set-option -g status-position bottom 

#set-option -g status-justify "absolute-centre"
set-option -g status-justify centre 

# Status colors
set-option -g status-style bg=$BG,fg=$FG

# Status contents
set-option -g status-left " "
set-option -g status-left-length 0
set-option -g status-right "#[fg=$GREEN]#[bg=$GREEN,fg=$BLACK] 󰐝  #S "

# Window list formats
set-option -g window-status-separator " "
set-option -g window-status-format "#[fg=$GRAY]#[fg=$FG,bg=$GRAY] #I:#W #[fg=$GRAY,bg=$BG]"
set-option -g window-status-current-format "#[fg=$GREEN]#[fg=$BLACK,bg=$GREEN] #I:#W #[fg=$GREEN,bg=$BG]"

